#使用的公式
## 公式一
公式
$\int_a^b f(x)=0$

In [7]:
import numpy
a = numpy.random.normal(size=(3,4))
print a

[[ 1.49813524  0.37239316 -0.00578256  0.08208941]
 [ 0.72593761 -0.5581946   0.09264468 -1.21714369]
 [ 1.55233655  1.69992015  1.0412069   0.70341767]]


这段代码的作用